import { Link, useLoaderData } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import prisma from "../db.server";

/**
 * /app/agent/reports — list recent SeoReport rows for this shop.
 *
 * Reports are written by the Python signal-pull pipeline (agent/).
 * This page is read-only; it never runs pulls itself. The Python CLI
 * (`glitch-seo-agent report`) is the only writer.
 */
export const loader = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const reports = await prisma.seoReport.findMany({
    where: { siteId: session.shop },
    orderBy: { createdAt: "desc" },
    take: 30,
    select: {
      id: true,
      createdAt: true,
      period: true,
      kind: true,
      platform: true,
      summary: true,
      error: true,
    },
  });
  return { reports };
};

export default function Reports() {
  const { reports } = useLoaderData();
  return (
    <s-page heading="SEO reports" backAction={{ content: "Back", url: "/app" }}>
      <s-section heading="Why this exists">
        <s-paragraph>
          Reports are generated by the Python signal-pull pipeline — Search
          Console traffic, PageSpeed Insights scores, and Natural Language
          entity extraction, all written to the same database the Shopify
          app reads. Runs daily (cron) plus on demand from the command line.
        </s-paragraph>
      </s-section>

      <s-section heading={`${reports.length} recent reports`}>
        {reports.length === 0 ? (
          <s-paragraph>
            No reports yet. Run <code>uv run glitch-seo-agent report --all</code>{" "}
            from <code>agent/</code> to generate your first.
          </s-paragraph>
        ) : (
          <s-stack direction="block" gap="small">
            {reports.map((r) => {
              const s = r.summary || {};
              return (
                <s-stack key={r.id} direction="inline" gap="base">
                  <s-text>{new Date(r.createdAt).toLocaleString()}</s-text>
                  <s-badge tone="info">{r.period}</s-badge>
                  <s-badge tone="subdued">{r.kind}</s-badge>
                  {typeof s.clicks === "number" && (
                    <s-badge>{s.clicks} clicks</s-badge>
                  )}
                  {typeof s.impressions === "number" && (
                    <s-badge>{s.impressions.toLocaleString()} impressions</s-badge>
                  )}
                  {typeof s.psi_median_performance === "number" && (
                    <s-badge
                      tone={
                        s.psi_median_performance >= 0.9 ? "success" :
                        s.psi_median_performance >= 0.5 ? "attention" : "critical"
                      }
                    >
                      PSI {Math.round(s.psi_median_performance * 100)}
                    </s-badge>
                  )}
                  {r.error && <s-badge tone="critical">error</s-badge>}
                  <Link to={`/app/agent/reports/${r.id}`}>details →</Link>
                </s-stack>
              );
            })}
          </s-stack>
        )}
      </s-section>
    </s-page>
  );
}

export const headers = (headersArgs) => boundary.headers(headersArgs);
